version: '3.9'

services:
  metabase:
    image: metabase/metabase:v0.48.4
    restart: always
    volumes:
      - ./metabase-data:/metabase-data
      - ./plugins:/plugins
    ports:
      - 3000:3000
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
      ## Portgres Config
      # - MB_DB_TYPE=postgres
      # - MB_DB_DBNAME=postgres
      # - MB_DB_PORT=5432
      # - MB_DB_USER=admin
      # - MB_DB_PASS=1234
      # - MB_DB_HOST=localhost
      # ## Mongo Config
      # - MB_DB_TYPE=mongo
      # - MB_DB_DBNAME=admin
      # - MB_DB_PORT=27017
      # - MB_DB_USER=admin
      # - MB_DB_PASS=1234
      # - MB_DB_HOST=localhost
    depends_on:
      - mongo
      - postgres
    networks:
      - postgres-network

  postgres:
    image: postgres:14
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=1234
    networks:
      - postgres-network

  mongo:
    image: mongo:4.4
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_INITDB_DATABASE=mongo
      - MONGO_INITDB_USERNAME=admin
      - MONGO_INITDB_PASSWORD=1234
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge